### Créer un article
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4aXMubGV2YXNzZXVyLjc2QGdtYWlsLmNvbSIsImVtYWlsIjoiYWxleGlzLmxldmFzc2V1ci43NkBnbWFpbC5jb20iLCJpYXQiOjE3NDUzNDQ3ODZ9.oOkmthXlxGqNezgW9bCEHchIzNNJOAiyAyfe8JPcw9M
POST https://api.blog.aexils.ca/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Article génial",
  "content": "Contenu super intéressant écrit avec amour ✨"
}

### Lister tous les articles
GET http://localhost:3000/posts